stages:
  - build
  - codingstyle
  - badges
  
buildWindows:
  stage: build
  script:
    - .\tests\build\build.bat 1>buildLog.txt
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
  tags:
    - Windows7
  artifacts:
    paths:
      - lib\python373\GTlabPython373.dll
      - lib\python373\GTlabPython373.exp
      - lib\python373\GTlabPython373.lib
      - build\GTlabPython373.pdb
      - build\GTlabPython373.ilk
      - buildLog.txt
      - "New_BuildWarn-W.svg"
    expire_in: 1 week
    when: always

#buildWindowsQt512:
#  stage: build
#  script:
#    - .\tests\build\buildQt512.bat 1>buildLog.txt
#  tags:
#    - Win7Qt512
#  artifacts:
#    paths:
#      - lib\python373\GTlabPython373.dll
#      - lib\python373\GTlabPython373.lib
#      - buildLog.txt
#    expire_in: 1 week
#    when: always
    
nightlyBuildPy273:
  stage: build
  script:
    - .\tests\build\build-nightly273.bat
    - .\tests\build\copyHeaders273.bat
  tags:
    - Windows7
  only:
    - master

nightlyBuildPy373:
  stage: build
  script:
    - .\tests\build\build-nightly373.bat
    - .\tests\build\copyHeaders373.bat
  tags:
    - Windows7
  only:
    - master

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Windows7
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
      - "New_CodingStyle.svg"
    expire_in: 1 week
    
badges:
  stage: badges
  script:
    - .\tests\badges\badges.bat --bw .\codingStyleLog.txt .
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run lines $linenumber
    - .\tests\badges\badges.bat --run files $fileNumber
  tags:
    - Windows7
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
    expire_in: 1 week



