########################################################
############# GTlab Pipeline Version 2.1.0 #############
########################################################
# This is a slight changed version
# - PYVERSION variable to support the build using different Python versions
# - the Python version is appended to the build and test job names
# - debug build is not possible because PythonQt is not available as debug build

# These variables are defined in the CI project settings:
#  CATEGORY: 03_core_modules
#  PROFILENAME: gtlab_python.pro
#  TARGETDIRNAME: python37
#  TARGETNAME: GTlabPython37
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable
#   WIN_PYTHON
#   STABLE_MAJOR
#   STABLE_MINOR
#   UNSTABLE_MAJOR
#   UNSTABLE_MINOR

# Environment variables to use in the pipeline globally
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: none
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main_1_0$|^main_1_1$/
  STABLE_BRANCHES: /^master$/
  
  STABLE_PY_MAJOR: 3
  STABLE_PY_MINOR: 7
  
  UNSTABLE_PY_MAJOR: 3
  UNSTABLE_PY_MINOR: 9
  
  STABLE_TARGETDIR: python$STABLE_PY_MAJOR$STABLE_PY_MINOR
  UNSTABLE_TARGETDIR: python$UNSTABLE_PY_MAJOR$UNSTABLE_PY_MINOR
  
  # Name of the unstable branch (if it exists)
  #UNSTABLE_BRANCH: unstable_master

# inlcude some templates from this file
include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-1.yml'
    
stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - package
  - deploy
  - codequality
  - badges

findCodeBaseStatus:
  stage: .pre
  extends: 
    - .only-tags-parent
    - .findCodeBaseStatusTemplate
  tags:
    - Win10

triggerDeployment:
  stage: deploy
  extends: .only-tags-parent
  trigger:
    include: .gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  variables:
    STABLE_BASE: $BUILD_STABLE_BASE

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux

# build on Windows system
.winDebugArtifacts:
  artifacts:
    paths:
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPythonSetup-d.dll
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPythonSetup-d.lib
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPythonSetup-d.pdb
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPython$PY_MAJOR$PY_MINOR-d.dll
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPython$PY_MAJOR$PY_MINOR-d.lib
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPython$PY_MAJOR$PY_MINOR-d.pdb
      - include\python$PY_MAJOR$PY_MINOR\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always

.winReleaseArtifacts:
  artifacts:
    paths:
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPythonSetup.dll
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPythonSetup.lib
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPython$PY_MAJOR$PY_MINOR.dll
      - lib\python$PY_MAJOR$PY_MINOR\GTlabPython$PY_MAJOR$PY_MINOR.lib
      - include\python$PY_MAJOR$PY_MINOR\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always
    
winBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildWinDebug
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR: $STABLE_PY_MAJOR
    PY_MINOR: $STABLE_PY_MINOR
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "true"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCVARS_2017_PS 
    
winBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildWinDebug
    - .winDebugArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR: $UNSTABLE_PY_MAJOR
    PY_MINOR: $UNSTABLE_PY_MINOR
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "true"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCVARS_2019_PS

winBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildWinRelease
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR: $STABLE_PY_MAJOR
    PY_MINOR: $STABLE_PY_MINOR
    BUILDBATCH: "false"
    MAJOR_VERSION: $STABLE_MAJOR
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCVARS_2017_PS
 
winBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildWinRelease
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR: $UNSTABLE_PY_MAJOR
    PY_MINOR: $UNSTABLE_PY_MINOR
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "true"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCVARS_2019_PS
    
# build on Linux system
.linuxDebugArtifacts:
  artifacts:
    paths:
      - lib/python$PY_MAJOR$PY_MINOR/libGTlabPythonSetup-d.so*
      - lib/python$PY_MAJOR$PY_MINOR/libGTlabPython$PY_MAJOR$PY_MINOR-d.so*
      - include/python$PY_MAJOR$PY_MINOR/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
    
.linuxReleaseArtifacts:
  artifacts:
    paths:
      - lib/python$PY_MAJOR$PY_MINOR/libGTlabPythonSetup.so*
      - lib/python$PY_MAJOR$PY_MINOR/libGTlabPython$PY_MAJOR$PY_MINOR.so*
      - include/python$PY_MAJOR$PY_MINOR/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
    
linuxBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildLinuxDebug
    - .linuxDebugArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR: $STABLE_PY_MAJOR
    PY_MINOR: $STABLE_PY_MINOR
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildLinuxDebug 
    - .linuxDebugArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR: $UNSTABLE_PY_MAJOR
    PY_MINOR: $UNSTABLE_PY_MINOR
    BUILDUNITTESTS: "true"
    BUILDBATCH: "false"
    MAJOR_VERSION: $UNSTABLE_MAJOR
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake
 
linuxBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildLinuxRelease 
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR: $STABLE_PY_MAJOR
    PY_MINOR: $STABLE_PY_MINOR
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildLinuxRelease 
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR: $UNSTABLE_PY_MAJOR
    PY_MINOR: $UNSTABLE_PY_MINOR
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake


# run tests using the binary built before
testWin:
  stage: test
  extends: 
    - .stable-debug
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  needs: 
    - winBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWinUnstable:
  stage: unstableTest
  extends:
    - .unstable-debug  
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt515.bat
    - get-content CoverageReport*\index.html
  needs: 
    - winBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux:
  stage: test
  extends: 
    - .stable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinuxUnstable:
  stage: unstableTest
  extends: 
    - .unstable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    LINUX_QT_DIR: /opt/Qt/5.15.2/gcc_64

# run package jobs
.package:
  stage: package
  tags:
    - Linux
  script:
    - mkdir pkg
    - mkdir -p pkg/$BINDIR
    - mkdir -p pkg/$BINDEBUGDIR
    - mkdir -p pkg/lib/$SUBDIR
    # copy all runtime libs into bindirs
    - mv lib/$SUBDIR/*-d.dll pkg/$BINDEBUGDIR 2> /dev/null || `:`
    - mv lib/$SUBDIR/*-d.so* pkg/$BINDEBUGDIR 2> /dev/null || `:`
    - mv lib/$SUBDIR/*.dll pkg/$BINDIR 2> /dev/null || `:`
    - mv lib/$SUBDIR/*.so* pkg/$BINDIR 2> /dev/null || `:`
    # copy all libs into pkg/lib
    - mv lib/$SUBDIR/*.lib pkg/lib/$SUBDIR 2> /dev/null || `:`
    - cp pkg/$BINDIR/*.so* pkg/lib/$SUBDIR 2> /dev/null || `:`
    - cp pkg/$BINDEBUGDIR/*.so* pkg/lib/$SUBDIR 2> /dev/null || `:`
    # move include and libdir into package
    - mv include/ pkg/
    # show package contents
    - find pkg/
  artifacts:
    paths:
    - pkg
  variables:
    BINDIR: bin/modules
    BINDEBUGDIR: binDebug/modules
    SUBDIR: $STABLE_TARGETDIR

packageWinStable:
  extends:
    - .package
    - .stable-release
  needs:
    - job: winBuildDebug
    - job: winBuildRelease
      optional: true

packageWinUnstable:
  extends:
    - .package
    - .unstable-release
  needs:
    - job: winBuildDebugUnstable
    - job: winBuildReleaseUnstable
      optional: true
  variables:
    SUBDIR: $UNSTABLE_TARGETDIR

packageLinuxStable:
  extends:
    - .package
    - .stable-release
  needs:
    - job: linuxBuildDebug
    - job: linuxBuildRelease
      optional: true

packageLinuxUnstable:
  extends:
    - .package
    - .unstable-release
  needs:
    - job: linuxBuildDebugUnstable
    - job: linuxBuildReleaseUnstable
      optional: true
  variables:
    SUBDIR: $UNSTABLE_TARGETDIR
    
packageXml:
  stage: package
  extends: .packageTemplate

# deployment
.stable-tag:
  rules:
    - if: $CI_COMMIT_TAG != null && $STABLE_BASE != null && $STABLE_BASE == "True"

.unstable-tag:
  rules:
    - if: $CI_COMMIT_TAG != null && $UNSTABLE_BRANCH == null && $STABLE_BASE != null && $STABLE_BASE == "True"
    - if: $CI_COMMIT_TAG != null && $UNSTABLE_BRANCH != null && $STABLE_BASE != null && $STABLE_BASE == "False"

.deploy:
  script:
    - robocopy pkg C:\deployment\$PLATFORMNAME\$CATEGORY\$CI_PROJECT_NAME\$RELEASESTATUS\$CI_COMMIT_TAG /MIR; if ($lastexitcode -lt 4) { $global:LASTEXITCODE = $null }
  variables:
    PLATFORMNAME: windows
    RELEASESTATUS: stable

deployWinStable:
  stage: deploy
  extends:
    - .stable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - packageWinStable
  variables:
    PLATFORMNAME: windows
    RELEASESTATUS: stable

deployWinUnstable:
  stage: deploy
  extends:
    - .unstable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - packageWinUnstable
  variables:
    PLATFORMNAME: windows
    RELEASESTATUS: unstable

deployLinuxStable:
  stage: deploy
  extends:
    - .stable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - packageLinuxStable
  variables:
    PLATFORMNAME: linux
    RELEASESTATUS: stable

deployLinuxUnstable:
  stage: deploy
  extends:
    - .unstable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - packageLinuxUnstable
  variables:
    PLATFORMNAME: linux
    RELEASESTATUS: unstable

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate

cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate

pages:
  stage: badges
  extends: .pageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - winBuildDebug
    - linuxBuildDebug
    - testWin
    - testLinux
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - winBuildDebugUnstable
    - linuxBuildDebugUnstable
    - testWinUnstable
    - testLinuxUnstable
    - codingstyle
