########################################################
############# GTlab Pipeline Version 2.1.0 #############
########################################################
# This is a slight changed version
# - PYVERSION variable to support the build using different Python versions
# - the Python version is appended to the build and test job names
# - debug build is not possible because PythonQt is not available as debug build

# These variables are defined in the CI project settings:
#  CATEGORY: 03_core_modules
#  PROFILENAME: gtlab_python.pro
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable
#   WIN_PYTHON
#   STABLE_MAJOR
#   STABLE_MINOR
#   UNSTABLE_MAJOR
#   UNSTABLE_MINOR

# Environment variables to use in the pipeline globally
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: none
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete several branch names with |
  # e.g. /^main_1_0$|^main_1_1$/
  STABLE_BRANCHES: /^master$/
  
  PY_MAJOR: 3
  PY_MINOR: 7
  
  PY_MAJOR_UNSTABLE: 3
  PY_MINOR_UNSTABLE: 9
  
  TARGETNAME: GTlabPython$PY_MAJOR$PY_MINOR
  TARGETNAME_UNSTABLE: GTlabPython$PY_MAJOR_UNSTABLE$PY_MINOR_UNSTABLE
  
  TARGETDIRNAME: python$PY_MAJOR$PY_MINOR
  TARGETDIRNAME_UNSTABLE: python$PY_MAJOR_UNSTABLE$PY_MINOR_UNSTABLE
  
  GT_MODULE_ID: "Python Module (Python $PY_MAJOR.$PY_MINOR)"
  GT_MODULE_ID_UNSTABLE: "Python Module (Python $PY_MAJOR_UNSTABLE.$PY_MINOR_UNSTABLE)"

  TARGETNAME_SETUP_MODULE: GTlabPythonSetup

  # Name of the unstable branch (if it exists)
  #UNSTABLE_BRANCH: unstable_master

# inlcude some templates from this file
include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-1.yml'
    
stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - package
  - deploy
  - codequality
  - badges

findCodeBaseStatus:
  stage: .pre
  extends: 
    - .only-tags-parent
    - .findCodeBaseStatusTemplate
  tags:
    - Win10

triggerDeployment:
  stage: deploy
  extends: .only-tags-parent
  trigger:
    include: .gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  variables:
    STABLE_BASE: $BUILD_STABLE_BASE

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux

# build on Windows system
.winDebugArtifacts:
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME_SETUP_MODULE-d.dll
      - lib\$TARGETDIRNAME\$TARGETNAME_SETUP_MODULE-d.lib
      - lib\$TARGETDIRNAME\$TARGETNAME_SETUP_MODULE-d.pdb
      - lib\$TARGETDIRNAME\$TARGETNAME-d.dll
      - lib\$TARGETDIRNAME\$TARGETNAME-d.lib
      - lib\$TARGETDIRNAME\$TARGETNAME-d.pdb
      - include\$TARGETDIRNAME\
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
    expire_in: 1 week
    when: always

.winReleaseArtifacts:
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME_SETUP_MODULE.dll
      - lib\$TARGETDIRNAME\$TARGETNAME_SETUP_MODULE.lib
      - lib\$TARGETDIRNAME\$TARGETNAME.dll
      - lib\$TARGETDIRNAME\$TARGETNAME.lib
      - include\$TARGETDIRNAME\
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always
    
winBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildWinDebug
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "true"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCVARS_2017_PS 
    
winBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildWinDebug
    - .winDebugArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "true"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCVARS_2019_PS
    TARGETNAME: $TARGETNAME_UNSTABLE
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    PY_MAJOR: $PY_MAJOR_UNSTABLE
    PY_MINOR: $PY_MINOR_UNSTABLE

winBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildWinRelease
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    BUILDBATCH: "false"
    MAJOR_VERSION: $STABLE_MAJOR
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCVARS_2017_PS
 
winBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildWinRelease
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "true"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCVARS_2019_PS
    TARGETNAME: $TARGETNAME_UNSTABLE
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    PY_MAJOR: $PY_MAJOR_UNSTABLE
    PY_MINOR: $PY_MINOR_UNSTABLE

# build on Linux system
.linuxDebugArtifacts:
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME_SETUP_MODULE-d.so*
      - lib/$TARGETDIRNAME/lib$TARGETNAME-d.so*
      - include/$TARGETDIRNAME/
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
    
.linuxReleaseArtifacts:
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME_SETUP_MODULE.so*
      - lib/$TARGETDIRNAME/lib$TARGETNAME.so*
      - include/$TARGETDIRNAME/
      - meta/
      - examples/
    when: always
    expire_in: 1 week
    
linuxBuildDebug:
  stage: build
  extends: 
    - .stable-debug
    - .buildLinuxDebug
    - .linuxDebugArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildDebugUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildLinuxDebug 
    - .linuxDebugArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    BUILDUNITTESTS: "true"
    BUILDBATCH: "false"
    MAJOR_VERSION: $UNSTABLE_MAJOR
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake
    TARGETNAME: $TARGETNAME_UNSTABLE
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    PY_MAJOR: $PY_MAJOR_UNSTABLE
    PY_MINOR: $PY_MINOR_UNSTABLE

linuxBuildRelease:
  stage: build
  extends: 
    - .stable-release
    - .buildLinuxRelease 
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildReleaseUnstable:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildLinuxRelease 
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake
    TARGETNAME: $TARGETNAME_UNSTABLE
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    PY_MAJOR: $PY_MAJOR_UNSTABLE
    PY_MINOR: $PY_MINOR_UNSTABLE

# run tests using the binary built before
testWin:
  stage: test
  extends: 
    - .stable-debug
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  needs: 
    - winBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWinUnstable:
  stage: unstableTest
  extends:
    - .unstable-debug  
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt515.bat
    - get-content CoverageReport*\index.html
  needs: 
    - winBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux:
  stage: test
  extends: 
    - .stable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebug
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinuxUnstable:
  stage: unstableTest
  extends: 
    - .unstable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstable
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    LINUX_QT_DIR: /opt/Qt/5.15.2/gcc_64

# run package jobs
winPackageRelease:
  stage: package
  extends:
    - .pkgTemplate
    - .stable-release
  needs:
    - winBuildRelease

winPackageDebug:
  stage: package
  extends:
    - .pkgTemplate
    - .stable-debug
  needs:
    - winBuildDebug
  variables:
    BINDIR: binDebug/modules

winPackageReleaseUnstable:
  stage: package
  extends:
    - .pkgTemplate
    - .unstable-release
  needs:
    - winBuildReleaseUnstable
  variables:
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    GT_MODULE_ID: $GT_MODULE_ID_UNSTABLE

winPackageDebugUnstable:
  stage: package
  extends:
    - .pkgTemplate
    - .unstable-debug
  needs:
    - winBuildDebugUnstable
  variables:
    BINDIR: binDebug/modules
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    GT_MODULE_ID: $GT_MODULE_ID_UNSTABLE
    
linuxPackageRelease:
  stage: package
  extends:
    - .pkgTemplate
    - .stable-release
  needs:
    - linuxBuildRelease
    
linuxPackageDebug:
  stage: package
  extends:
    - .pkgTemplate
    - .stable-debug
  needs:
    - linuxBuildDebug
  variables:
    BINDIR: binDebug/modules

linuxPackageReleaseUnstable:
  stage: package
  extends:
    - .pkgTemplate
    - .unstable-release
  needs:
    - linuxBuildReleaseUnstable
  variables:
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    GT_MODULE_ID: $GT_MODULE_ID_UNSTABLE

linuxPackageDebugUnstable:
  stage: package
  extends:
    - .pkgTemplate
    - .unstable-debug
  needs:
    - linuxBuildDebugUnstable
  variables:
    BINDIR: binDebug/modules
    TARGETDIRNAME: $TARGETDIRNAME_UNSTABLE
    GT_MODULE_ID: $GT_MODULE_ID_UNSTABLE
    
packageXml:
  stage: package
  extends: .packageTemplate

# deployment
.stable-tag:
  rules:
    - if: $CI_COMMIT_TAG != null && $STABLE_BASE != null && $STABLE_BASE == "True"

.unstable-tag:
  rules:
    - if: $CI_COMMIT_TAG != null && $UNSTABLE_BRANCH == null && $STABLE_BASE != null && $STABLE_BASE == "True"
    - if: $CI_COMMIT_TAG != null && $UNSTABLE_BRANCH != null && $STABLE_BASE != null && $STABLE_BASE == "False"

.deploy:
  script:
    - robocopy pkg C:\deployment\$PLATFORMNAME\$CATEGORY\$CI_PROJECT_NAME\$RELEASESTATUS\$CI_COMMIT_TAG /MIR; if ($lastexitcode -lt 4) { $global:LASTEXITCODE = $null }
  variables:
    PLATFORMNAME: windows
    RELEASESTATUS: stable

winDeployStable:
  stage: deploy
  extends:
    - .stable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - winPackageDebug
    - winPackageRelease
  variables:
    PLATFORMNAME: windows
    RELEASESTATUS: stable

winDeployUnstable:
  stage: deploy
  extends:
    - .unstable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - winPackageDebugUnstable
    - winPackageReleaseUnstable
  variables:
    PLATFORMNAME: windows
    RELEASESTATUS: unstable

linuxDeployStable:
  stage: deploy
  extends:
    - .stable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - linuxPackageDebug
    - linuxPackageRelease
  variables:
    PLATFORMNAME: linux
    RELEASESTATUS: stable

linuxDeployUnstable:
  stage: deploy
  extends:
    - .unstable-tag
    - .deploy
  tags:
    - Win10
  needs:
    - linuxPackageDebugUnstable
    - linuxPackageReleaseUnstable
  variables:
    PLATFORMNAME: linux
    RELEASESTATUS: unstable

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate

cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate

pages:
  stage: badges
  extends: .pageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - winBuildDebug
    - linuxBuildDebug
    - testWin
    - testLinux
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - winBuildDebugUnstable
    - linuxBuildDebugUnstable
    - testWinUnstable
    - testLinuxUnstable
    - codingstyle

