########################################################
###############GTlab Pipeline Version 1.5.1 ############
########################################################
# This is a slight changed version
# - PYVERSION variable to support the build using different Python versions
# - the Python version is appended to the build and test job names
# - debug build is not possible because PythonQt is not available as debug build


# These variables are defined in the CI project settings:
#  CATEGORY: 03_core_modules
#  PROFILENAME: gtlab_python.pro
#  TARGETDIRNAME: python37
#  TARGETNAME: GTlabPython37
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable

# Environment variables to use in the pipeline globally
variables:
  PIPELINEVERSION: "1.5.1"
  GIT_SUBMODULE_STRATEGY: none

# inlcude some templates from this file
include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - copy
  - codequality
  - package
  - badges

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows
  only:
    - master 

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux
  only:
    - master

# build on Windows system
windowsBuildDebugPy37:
  stage: build
  extends: 
    - .buildWinSub
  tags:
    - Win10
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME-d.dll
      - lib\$TARGETDIRNAME\$TARGETNAME-d.lib
      - lib\$TARGETDIRNAME\$TARGETNAME-d.pdb
      - include\$TARGETDIRNAME\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog512.txt
    expire_in: 1 week
    when: always
  variables:
    PYVERSION: "37"
    BUILDBATCH: "true"
    BUILDMODE: release
    BUILDUNITTESTS: "true"
  parallel:
    matrix: 
      - DEVTOOLS: [$DEVTOOLS_Win_Stable, $DEVTOOLS_Win_Unstable]

windowsBuildReleasePy37:
  stage: build
  extends: 
    - .buildWinSub
  tags:
    - Win10
  only:
    - master
    - tags
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME.dll
      - lib\$TARGETDIRNAME\$TARGETNAME.lib
      - include\$TARGETDIRNAME\*.h
    expire_in: 1 week
    when: always
  variables:
    PYVERSION: "37"
    BUILDBATCH: "false"
    BUILDMODE: release
    BUILDUNITTESTS: "false"
  parallel:
    matrix: 
      - DEVTOOLS: [$DEVTOOLS_Win_Stable, $DEVTOOLS_Win_Unstable]  
    
# build on Linux system
linuxBuildDebugPy37:
  stage: build
  extends: 
    - .buildLinux
  tags:
    - Linux
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME-d.so
      - include/$TARGETDIRNAME/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    BUILDMODE: release
    BUILDUNITTESTS: "true"
  parallel:
    matrix: 
      - DEVTOOLS: [$DEVTOOLS_Linux_Stable, $DEVTOOLS_Linux_Unstable] 

linuxBuildReleasePy37:
  stage: build
  extends: 
    - .buildLinux
  tags:
    - Linux
  only:
    - master
    - tags
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME.so*
      - include/$TARGETDIRNAME/*.h
    expire_in: 1 week
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    BUILDMODE: release
    BUILDUNITTESTS: "false"
  parallel:
    matrix: 
      - DEVTOOLS: [$DEVTOOLS_Linux_Stable, $DEVTOOLS_Linux_Unstable]   
    
# run tests using the binary built before
testWin512Py37:
  extends: .winTestTemplateSub
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  needs: ["windowsBuildDebugPy37: [$DEVTOOLS_Win_Stable]"]
  dependencies: ["windowsBuildDebugPy37: [$DEVTOOLS_Win_Stable]"]
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWin512UnstablePy37:
  extends: .winTestTemplateSub
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html

  needs: ["windowsBuildDebugPy37: [$DEVTOOLS_Win_Unstable]"]
  dependencies: ["windowsBuildDebugPy37: [$DEVTOOLS_Win_Unstable]"]
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux512Py37:
  extends: .linuxTestTemplateSub
  needs: ["linuxBuildDebugPy37: [$DEVTOOLS_Linux_Stable]"]
  dependencies:
    - "linuxBuildDebugPy37: [$DEVTOOLS_Linux_Stable]"
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinux512UnstablePy37:
  extends: .linuxTestTemplateSub
  needs: ["linuxBuildDebugPy37: [$DEVTOOLS_Linux_Unstable]"]
  dependencies:
    - "linuxBuildDebugPy37: [$DEVTOOLS_Linux_Unstable]"
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable   

# copy files to servers
copyToNightlyBuildWin:
  extends: .copyNightlyTemplateSub
  dependencies: ["windowsBuildReleasePy37: [$DEVTOOLS_Win_Stable]"]
  allow_failure: true

copyForDeploymentWin:
  extends: .copyDeployTemplateSub
  dependencies:
    - "windowsBuildDebugPy37: [$DEVTOOLS_Win_Stable]"
    - "windowsBuildReleasePy37: [$DEVTOOLS_Win_Stable]"
  variables:
    PLATFORMNAME:  windows
    RELEASESTATUS: stable 

copyForDeploymentWinUnstable:
  extends: .copyDeployTemplateSub
  dependencies: 
    - "windowsBuildDebugPy37: [$DEVTOOLS_Win_Unstable]"
    - "windowsBuildReleasePy37: [$DEVTOOLS_Win_Unstable]"
  variables:
    PLATFORMNAME:  windows
    RELEASESTATUS: unstable
 
copyForDeploymentLinux:
  extends: .copyDeployTemplateSub
  dependencies:
    - "linuxBuildDebugPy37: [$DEVTOOLS_Linux_Stable]"
    - "linuxBuildReleasePy37: [$DEVTOOLS_Linux_Stable]"
  variables:
    PLATFORMNAME:  linux
    RELEASESTATUS: stable

copyForDeploymentLinuxUnstable:
  extends: .copyDeployTemplateSub
  dependencies:
    - "linuxBuildDebugPy37: [$DEVTOOLS_Linux_Unstable]"
    - "linuxBuildReleasePy37: [$DEVTOOLS_Linux_Unstable]"
  variables:
    PLATFORMNAME:  linux
    RELEASESTATUS: unstable

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate 
  except:
    - tags
 
cppcheck:
  stage: codequality
  extends: .cppCheckTemplate 
   
pages:
  stage: badges
  extends: .pageTemplate 
  only:
    - master
    - tag

package:
  stage: package
  extends: .packageTemplateSub
  only:
    - tags

# badges
badges:
  stage: badges
  extends: .badgeTemplate 
  dependencies:
    - "windowsBuildDebugPy37: [$DEVTOOLS_Win_Unstable]"
    - "linuxBuildDebugPy37: [$DEVTOOLS_Linux_Stable]"
    - testWin512Py37
    - testLinux512Py37
    - codingstyle
  except:
    - tags
