stages:
  - build
  - codingstyle
  - badges
  
buildWindows:
  stage: build
  script:
    - .\tests\build\build.bat 1>buildLog.txt
  tags:
    - Windows7
  artifacts:
    paths:
      - lib\python373\GTlabPython373.dll
      - lib\python373\GTlabPython373.exp
      - lib\python373\GTlabPython373.lib
      - build\GTlabPython373.pdb
      - build\GTlabPython373.ilk
      - buildLog.txt
    when: always  
    expire_in: 1 week

nightlyBuildPy273:
  stage: build
  script:
    - .\tests\build\build-nightly273.bat
    - .\tests\build\copyHeaders273.bat
  tags:
    - Windows7
  only:
    - master

nightlyBuildPy373:
  stage: build
  script:
    - .\tests\build\build-nightly373.bat
    - .\tests\build\copyHeaders373.bat
  tags:
    - Windows7
  only:
    - master

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Windows7
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week

badges:
  stage: badges
  script:
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Windows7
  artifacts:
    paths:
      - "New_BuildWarn-W.svg"
      - "New_CodingStyle.svg"
    

