########################################################
############# GTlab Pipeline Version 2.1.0 #############
########################################################
# This is a slight changed version
# - PYVERSION variable to support the build using different Python versions
# - the Python version is appended to the build and test job names
# - debug build is not possible because PythonQt is not available as debug build

# These variables are defined in the CI project settings:
#  CATEGORY: 03_core_modules
#  PROFILENAME: gtlab_python.pro
#  TARGETDIRNAME: python37
#  TARGETNAME: GTlabPython37
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable
#   WIN_PYTHON
#   STABLE_MAJOR
#   STABLE_MINOR
#   UNSTABLE_MAJOR
#   UNSTABLE_MINOR

# Environment variables to use in the pipeline globally
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: none
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main_1_0$|^main_1_1$/
  STABLE_BRANCHES: /^master$/
  
  # Name of the unstable branch (if it exists)
  #UNSTABLE_BRANCH: unstable_master

# inlcude some templates from this file
include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-1.yml'
    
stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - deploy
  - codequality
  - package
  - badges

findCodeBaseStatus:
  stage: .pre
  extends: 
    - .only-tags-parent
    - .findCodeBaseStatusTemplate
  tags:
    - Win10

triggerDeployment:
  stage: deploy
  extends: .only-tags-parent
  trigger:
    include: .gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  variables:
    STABLE_BASE: $BUILD_STABLE_BASE

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux

# build on Windows system
.winDebugArtifacts:
  artifacts:
    paths:
      - lib\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\GTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION-d.dll
      - lib\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\GTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION-d.lib
      - lib\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\GTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION-d.pdb
      - include\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always

.winReleaseArtifacts:
  artifacts:
    paths:
      - lib\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\GTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION.dll
      - lib\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\GTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION.lib
      - include\python$PY_MAJOR_VERSION$PY_MINOR_VERSION\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always
    
windowsBuildDebugPy37:
  stage: build
  extends: 
    - .stable-debug
    - .buildWinDebug
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 7
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "true"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCVARS_2017_PS 
    
windowsBuildDebugUnstablePy39:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildWinDebug
    - .winDebugArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 9
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "true"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCVARS_2019_PS

windowsBuildReleasePy37:
  stage: build
  extends: 
    - .stable-release
    - .buildWinRelease
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 7
    BUILDBATCH: "false"
    MAJOR_VERSION: $STABLE_MAJOR
    DEVTOOLS: $DEVTOOLS_Win_Stable
    JOM_PATH: $JOM_PATH_512
    QMAKE_PATH: $QMAKE_PATH_512
    VCvarsall: $VCVARS_2017_PS
 
windowsBuildReleaseUnstablePy39:
  stage: unbuild
  extends: 
    - .unstable-release
    - .buildWinRelease
    - .winReleaseArtifacts
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 9
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "true"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    JOM_PATH: $JOM_PATH_515
    QMAKE_PATH: $QMAKE_PATH_515
    VCvarsall: $VCVARS_2019_PS
    
# build on Linux system
.linuxDebugArtifacts:
  artifacts:
    paths:
      - lib/python$PY_MAJOR_VERSION$PY_MINOR_VERSION/libGTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION-d.so
      - include/python$PY_MAJOR_VERSION$PY_MINOR_VERSION/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
    
.linuxReleaseArtifacts:
  artifacts:
    paths:
      - lib/python$PY_MAJOR_VERSION$PY_MINOR_VERSION/libGTlabPython$PY_MAJOR_VERSION$PY_MINOR_VERSION.so
      - include/python$PY_MAJOR_VERSION$PY_MINOR_VERSION/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
    
linuxBuildDebugPy37:
  stage: build
  extends: 
    - .stable-debug
    - .buildLinuxDebug
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 7
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "false"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildDebugUnstablePy39:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildLinuxDebug 
    - .linuxDebugArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 9
    BUILDUNITTESTS: "true"
    BUILDBATCH: "false"
    MAJOR_VERSION: $UNSTABLE_MAJOR
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake
 
linuxBuildReleasePy37:
  stage: build
  extends: 
    - .stable-release
    - .buildLinuxRelease 
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 7
    MAJOR_VERSION: $STABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Stable
    QMAKE_EXECUTABLE: /opt/Qt/5.12.5/gcc_64/bin/qmake

linuxBuildReleaseUnstablePy39:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildLinuxRelease 
    - .linuxReleaseArtifacts
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PY_MAJOR_VERSION: 3
    PY_MINOR_VERSION: 9
    MAJOR_VERSION: $UNSTABLE_MAJOR
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    QMAKE_EXECUTABLE: /opt/Qt/5.15.2/gcc_64/bin/qmake


# run tests using the binary built before
testWinPy37:
  stage: test
  extends: 
    - .stable-debug
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  needs: 
    - windowsBuildDebugPy37
  dependencies: 
    - windowsBuildDebugPy37
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWinUnstablePy39:
  stage: unstableTest
  extends:
    - .unstable-debug  
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt515.bat
    - get-content CoverageReport*\index.html
  needs: 
    - windowsBuildDebugUnstablePy39
  dependencies: 
    - windowsBuildDebugUnstablePy39
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinuxPy37:
  stage: test
  extends: 
    - .stable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugPy37
  dependencies:
    - linuxBuildDebugPy37
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinuxUnstablePy39:
  stage: unstableTest
  extends: 
    - .unstable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstablePy39
  dependencies:
    - linuxBuildDebugUnstablePy39
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
    LINUX_QT_DIR: /opt/Qt/5.15.2/gcc_64

# deployment
createJobs:
  stage: deploy
  extends:
    - .createJobsTemplate
  dependencies: []
  variables:
    WinReStableJob: windowsBuildReleasePy37
    WinReUnstableJob: windowsBuildReleaseUnstablePy39
    WinDeStableJob: windowsBuildDebugPy37
    WinDeUnstableJob: windowsBuildDebugUnstablePy39
    LinReStableJob: linuxBuildReleasePy37
    LinReUnstableJob: linuxBuildReleaseUnstablePy39
    LinDeStableJob: linuxBuildDebugPy37
    LinDeUnstableJob: linuxBuildDebugUnstablePy39

triggerJobs:
  stage: deploy
  extends: .only-tags-child
  needs:
    - createJobs
  trigger:
    include:
      - artifact: deploy.yml
        job: createJobs
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate

cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate

pages:
  stage: badges
  extends: .pageTemplate

package:
  stage: package
  extends: .packageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugPy37
    - linuxBuildDebugPy37
    - testWinPy37
    - testLinuxPy37
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugUnstablePy39
    - linuxBuildDebugUnstablePy39
    - testWinUnstablePy39
    - testLinuxUnstablePy39
    - codingstyle
