stages:
  - build
  - test
  - codingstyle
  - badges

buildWindows:
  stage: build
  script:
    - .\tests\build\build.bat 1>buildLog.txt
  tags:
    - Windows7
  artifacts:
    paths:
      - lib\python373\GTlabPython373.dll
      - lib\python373\GTlabPython373.exp
      - lib\python373\GTlabPython373.lib
      - build\GTlabPython373.pdb
      - build\GTlabPython373.ilk
      - build\GTlabUnitTest.exe
      - build\GTlabUnitTest.pdb

      - buildLog.txt
    expire_in: 1 week

nightlyBuildPy273:
  stage: build
  script:
    - .\tests\build\build-nightly273.bat
    - .\tests\build\copyHeaders273.bat
  tags:
    - Windows7
  only:
    - master

nightlyBuildPy373:
  stage: build
  script:
    - .\tests\build\build-nightly373.bat
    - .\tests\build\copyHeaders373.bat
  tags:
    - Windows7
  only:
    - master
    
buildWindowsQt512:
  stage: build
  script:
    - .\tests\build\buildQt512.bat 1>buildLogQt512.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - lib\python373\GTlabPython373-d.dll
      - lib\python373\GTlabPython373-d.lib
      - lib\python373\GTlabPython373-d.pdb
      - lib\python373\GTlabPython373-d.ilk
      - lib\python373\GTlabPython373-d.exp
      - buildLogQt512.txt
    expire_in: 1 week
    when: always

nightlyBuildQt512Py373:
  stage: build
  script:
    - .\tests\build\build-nightlyQt512Py373.bat
    - .\tests\build\copyHeadersQt512Py373.bat
  tags:
    - Win7Qt512
  only:
    - master
  artifacts:
    paths:
      - lib\python373\GTlabPython373.dll
      - lib\python373\GTlabPython373.lib
      - include/python373/*.h  
    expire_in: 1 week
    when: always

# run tests using the binary built before
testWin:
  stage: test
  script:
    - .\tests\unittests\runUnittests.bat
  dependencies:
    - buildWindows
  tags:
    - Windows7
  artifacts:
    paths:
      - "GTlabUnitTestCoverage.xml"
      - "CoverageReport*"
      - "unittests.xml"
    reports:
      junit: unittests.xml

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Windows7
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week

badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run lines $linenumber
    - .\tests\badges\badges.bat --run files $fileNumber
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Windows7
  only:
    - master
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
      - "New_BuildWarn-W.svg"
      - "New_CodingStyle.svg"
      - "New_Coverage.svg"
