stages:
  - build
  - codingstyle
  
buildWindows:
  stage: build
  script:
    - .\tests\build\build.bat 1>buildLog.txt
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
  tags:
    - Windows7
  artifacts:
    paths:
      - build/GTlabPython.dll
      - build/GTlabPython.exp
      - build/GTlabPython.ilk
      - build/GTlabPython.lib
      - build/GTlabPython.pdb
      - "New_BuildWarn-W.svg"
    expire_in: 1 week
      
codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Windows7
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
      - "New_CodingStyle.svg"
    expire_in: 1 week
