stages:
  - build
  - test
  - codingstyle
  - badges
  - tagsBuild

# build on Windows system

buildWindowsQt512Py37:
  stage: build
  script:
    - .\tests\build\build-512.bat 1>buildLogQt512.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
#      - lib\python37\GTlabPython37-d.dll
#      - lib\python37\GTlabPython37-d.lib
#      - lib\python37\GTlabPython37-d.pdb
#      - lib\python37\GTlabPython37-d.ilk
#      - lib\python37\GTlabPython37-d.exp
#      - buildLogQt512.txt
      - lib\python37\GTlabPython37.dll
      - lib\python37\GTlabPython37.lib
      - lib\python37\GTlabPython37.pdb
      - lib\python37\GTlabPython37.ilk
      - lib\python37\GTlabPython37.exp
      - build\GTlabUnitTest.exe
      - build\GTlabUnitTest.pdb
      - buildLogQt512.txt
    expire_in: 1 week
    when: always

nightlyBuildQt512Py37:
  stage: build
  script:
    - .\tests\build\build-nightly-512-py37.bat
    - .\tests\build\copyHeaders-512-py37.bat
  tags:
    - Win7Qt512
  only:
    - master
  artifacts:
    paths:
      - lib\python37\GTlabPython37.dll
      - lib\python37\GTlabPython37.lib
      - include\python37\*.h  
    expire_in: 1 week
    when: always

# build on Linux system

buildLinuxPy37:
  stage: build
  script:
    - chmod a+rwx ./tests/build/build-py37.sh
    - ./tests/build/build-py37.sh |& tee linuxBuild.txt
  tags:
    - Linux
  except:
    - tags
  artifacts:
    paths:
      - build/GTlabUnitTest
      - lib/python373/libGTlabPython373.so*
      - linuxBuild.txt
    when: always  	
    expire_in: 1 week

nightlyBuildLinuxPy37:
  stage: build
  script:
    - chmod a+rwx ./tests/build/build-nightly-py37.sh
    - ./tests/build/build-nightly-py37.sh
  tags:
    - Linux
  only:
    - master
  except:
    - tags
  artifacts:
    paths:
      - lib/python373/libGTlabPython373.so*    
      - include/python373/*.h   	   
    expire_in: 1 week

# run tests using the binary built before

testWinQt512Py37:
  stage: test
  script:
    - .\tests\unittests\runUnittestsQt512.bat
  dependencies:
    - buildWindowsQt512Py37
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "unittests.xml"
    reports:
      junit: unittests.xml

testLinuxPy37:
  stage: test
  script:
    - chmod a+rwx ./tests/unittests/runUnittests.sh
    - ./tests/unittests/runUnittests.sh
  dependencies:
    - buildLinuxPy37
  tags:
    - Linux
  artifacts:
    paths:
      - "unittests.xml"
    reports:
      junit: unittests.xml
      
codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Win7Qt512
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week

badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run lines $linenumber
    - .\tests\badges\badges.bat --run files $fileNumber
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Win7Qt512
#  only:
#    - master
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
      - "New_BuildWarn-W.svg"
      - "New_CodingStyle.svg"
      - "New_Coverage.svg"

tagsBuildWin:
  stage: tagsBuild
  tags:
    - Win7Qt512
  script:
    - echo "first tag build"
  only:
    - tags
