# Environment variables to use in the pipeline globally
variables:
  PROFILENAME: gtlab_python.pro
  TARGETDIRNAME: python37
  
stages:
  - build
  - test
  - copy
  - codingstyle
  - badges

# build on Windows system

debugBuildWinPy37:
  stage: build
  script:
    - .\tests\build\build-512.bat 1>buildLog.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
#      - lib\python37\GTlabPython37-d.dll
#      - lib\python37\GTlabPython37-d.lib
#      - lib\python37\GTlabPython37-d.pdb
#      - lib\python37\GTlabPython37-d.ilk
#      - lib\python37\GTlabPython37-d.exp
#      - buildLogQt512.txt
      - lib\python37\GTlabPython37.dll
      - lib\python37\GTlabPython37.lib
      - lib\python37\GTlabPython37.pdb
      - lib\python37\GTlabPython37.ilk
      - lib\python37\GTlabPython37.exp
      - build\GTlabUnitTest.exe
      - build\GTlabUnitTest.pdb
      - buildLog.txt
    expire_in: 1 week
    when: always
  variables:
    PYVERSION: "37"
    BUILDBATCH: "true"
    BUILDMODE: release
    BUILDUNITTESTS: "true"
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"

releaseBuildWinPy37:
  stage: build
  script:
    - .\tests\build\build-512.bat
  tags:
    - Win7Qt512
  only:
    - master
    - tags
  artifacts:
    paths:
      - lib\python37\GTlabPython37.dll
      - lib\python37\GTlabPython37.lib
      - include\python37\*.h
    expire_in: 1 week
    when: always
  variables:
    PYVERSION: "37"
    BUILDBATCH: "false"
    BUILDMODE: release
    BUILDUNITTESTS: "false"
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"
    
# build on Linux system

debugBuildLinuxPy37:
  stage: build
  script:
    - chmod a+rwx ./tests/build/build-512.sh
    - ./tests/build/build-512.sh |& tee linuxBuild.txt
  tags:
    - Linux
  artifacts:
    paths:
      - build/GTlabUnitTest
      - lib/python37/libGTlabPython37.so*
      - linuxBuild.txt
    when: always
    expire_in: 1 week
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    BUILDMODE: release
    BUILDUNITTESTS: "true"
    DEVTOOLS: "/home/gitlab-runner/GTlab-Devtools/stable/1_6"

releaseBuildLinuxPy37:
  stage: build
  script:
    - chmod a+rwx ./tests/build/build-512.sh
    - ./tests/build/build-512.sh
  tags:
    - Linux
  only:
    - master
    - tags
  artifacts:
    paths:
      - lib/python37/libGTlabPython37.so*    
      - include/python37/*.h
    expire_in: 1 week
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    BUILDMODE: release
    BUILDUNITTESTS: "false"
    DEVTOOLS: "/home/gitlab-runner/GTlab-Devtools/stable/1_6/"
    
# run tests using the binary built before

testWinPy37:
  needs: ["debugBuildWinPy37"]
  stage: test
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  dependencies:
    - debugBuildWinPy37
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "unittests.xml"
      - "GTlabUnitTestCoverage.xml"  
      - CoverageReport* 
    reports:
      junit: unittests.xml
    expire_in: 1 week
  variables:
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"

testLinuxPy37:
  needs: ["debugBuildLinuxPy37"]
  stage: test
  script:
    - chmod a+rwx ./tests/unittests/runUnittests.sh
    - ./tests/unittests/runUnittests.sh
  dependencies:
    - debugBuildLinuxPy37
  tags:
    - Linux
  artifacts:
    paths:
      - "unittests.xml"
    reports:
      junit: unittests.xml

# copy file to servers

copyToNightlyBuildWin:
  needs: ["releaseBuildWinPy37"]
  stage: copy
  script:
    - .\tests\build\copyHeaders-nightlybuild.bat
  dependencies:
    - releaseBuildWinPy37
  tags:
    - Win7Qt512
  only:
    - master
  allow_failure: true
  variables:
    NIGHTLYBUILD: "G:\\AT-TW\\GTlab\\Nightly_Builds_512"

copyToInstallerServer:
  stage: copy
  script:
    - .\tests\build\copyHeaders-installer-py37.bat
  dependencies:
    - debugBuildWinPy37
    - releaseBuildWinPy37
  tags:
    - Win7Qt512
  only:
    - tags

# checking the coding style

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Win7Qt512
  except:
    - tags
  dependencies:
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week

# create the badges

badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - $linenumber = $linesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run lines $linenumber
    - .\tests\badges\badges.bat --run files $fileNumber
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .
  tags:
    - Win7Qt512
  except:
    - tags
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
      - "New_BuildWarn-W.svg"
      - "New_CodingStyle.svg"
      - "New_Coverage.svg"
