########################################################
###############GTlab Pipeline Version 1.5.1 ############
########################################################
# This is a slight changed version
# - PYVERSION variable to support the build using different Python versions
# - the Python version is appended to the build and test job names
# - debug build is not possible because PythonQt is not available as debug build


# These variables are defined in the CI project settings:
#  CATEGORY: 03_core_modules
#  PROFILENAME: gtlab_python.pro
#  TARGETDIRNAME: python37
#  TARGETNAME: GTlabPython37
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable

# Environment variables to use in the pipeline globally
variables:
  PIPELINEVERSION: "1.5.1"
  GIT_SUBMODULE_STRATEGY: none
  
  STABE_MAINS: /^master_1_6$|^master_1_7$|^master_1_8$|^master$/

# inlcude some templates from this file
include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - copy
  - codequality
  - package
  - badges

# Test update
mergeRequestPipelineJob:
  stage: update
  tags:
    - Win10
  script:
    - echo ${CI_PIPELINE_SOURCE}
    - echo "Merge Request Pipeline"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ $STABE_MAINS'

# Test update
branchPipelineJob:
  stage: update
  tags:
    - Win10
  script:
    - echo ${CI_PIPELINE_SOURCE}
    - echo "Branch Pipeline"
#  only:
#    - master
