########################################################
###############GTlab Pipeline Version 2.0.0 ############
########################################################
# This is a slight changed version
# - PYVERSION variable to support the build using different Python versions
# - the Python version is appended to the build and test job names
# - debug build is not possible because PythonQt is not available as debug build

# These variables are defined in the CI project settings:
#  CATEGORY: 03_core_modules
#  PROFILENAME: gtlab_python.pro
#  TARGETDIRNAME: python37
#  TARGETNAME: GTlabPython37
#  UNITTESTSNAME: GTlabUnitTest

# These variables are defined in the AT-TWK group settings:
#   DEVTOOLS_Linux_Stable
#   DEVTOOLS_Linux_Unstable
#   DEVTOOLS_Win_Stable 
#   DEVTOOLS_Win_Unstable
#   WIN_PYTHON
#   STABLE_MAJOR
#   STABLE_MINOR
#   UNSTABLE_MAJOR
#   UNSTABLE_MINOR

# Environment variables to use in the pipeline globally
variables:
  PIPELINEVERSION: "2.1.0"
  GIT_SUBMODULE_STRATEGY: none
  
  # Regulare expression pattern
  # enclose the branch name with ^ and $
  # separete severl branch names with |
  # e.g. /^main_1_0$|^main_1_1$/
  STABLE_BRANCHES: /^master$/
  
  # Name of the unstable branch (if it exists)
  #UNSTABLE_BRANCH: unstable_master

# inlcude some templates from this file
include:
  - project: 'at-twk/gitlab-templates'
    file: '/ci-templates/.ci-templates-2-1.yml'

stages:
  - update
  - build
  - test
  - regressionTest
  - unstableBuild
  - unstableTest
  - deploy
  - codequality
  - package
  - badges

findCodeBaseStatus:
  stage: .pre
  tags:
    - Win10
  extends: .findCodeBaseStatusTemplate

triggerDeployment:
  stage: deploy
  extends: .only-tags-parent
  trigger:
    include: .gitlab-ci.yml
    forward:
      pipeline_variables: true
    strategy: depend
  variables:
    STABLE_BASE: $BUILD_STABLE_BASE
    UNSTABLE_BASE: $BUILD_UNSTABLE_BASE

# DevTools update
devtoolsUpdateWindows:
  stage: update
  extends: .devToolsUpdateWindows

devtoolsUpdateLinux:
  stage: update
  extends: .devToolsUpdateLinux

# build on Windows system
windowsBuildDebugPy37:
  stage: build
  extends: 
    - .stable-debug
    - .buildWinDebug
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME.dll
      - lib\$TARGETDIRNAME\$TARGETNAME.lib
      - lib\$TARGETDIRNAME\$TARGETNAME.pdb
      - include\$TARGETDIRNAME\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog512.txt
    expire_in: 1 week
    when: always

  variables:
    PYVERSION: "37"
    BUILDBATCH: "true"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Win_Stable

windowsBuildDebugUnstablePy37:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildWinDebug
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  artifacts:
    paths:
      - lib\$TARGETDIRNAME\$TARGETNAME-d.dll
      - lib\$TARGETDIRNAME\$TARGETNAME-d.lib
      - lib\$TARGETDIRNAME\$TARGETNAME-d.pdb
      - include\$TARGETDIRNAME\*.h
      - build\$UNITTESTSNAME.exe
      - build\$UNITTESTSNAME.pdb
      - buildLog512.txt
    expire_in: 1 week
    when: always
  variables:
    PYVERSION: "37"
    BUILDBATCH: "true"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Win_Unstable

windowsBuildReleasePy37:
  stage: build
  extends: 
    - .stable-release
    - .buildWinRelease
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PYVERSION: "37"
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Win_Stable

windowsBuildReleaseUnstablePy37:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildWinRelease
  needs:
    - job: devtoolsUpdateWindows
      optional: true
  variables:
    PYVERSION: "37"
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Win_Unstable
    
# build on Linux system
linuxBuildDebugPy37:
  stage: build
  extends: 
    - .stable-debug
    - .buildLinuxDebug
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME.so
      - include/$TARGETDIRNAME/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Linux_Stable

linuxBuildDebugUnstablePy37:
  stage: unstableBuild
  extends: 
    - .unstable-debug
    - .buildLinuxDebug 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  artifacts:
    paths:
      - lib/$TARGETDIRNAME/lib$TARGETNAME.so
      - include/$TARGETDIRNAME/*.h
      - build/$UNITTESTSNAME
      - linuxBuild.txt
    when: always
    expire_in: 1 week
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    BUILDMODE: release
    DEVTOOLS: $DEVTOOLS_Linux_Unstable
 
linuxBuildReleasePy37:
  stage: build
  extends: 
    - .stable-release
    - .buildLinuxRelease 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Stable

linuxBuildReleaseUnstablePy37:
  stage: unstableBuild
  extends: 
    - .unstable-release
    - .buildLinuxRelease 
  needs:
    - job: devtoolsUpdateLinux
      optional: true
  variables:
    PYVERSION: 37
    BUILDBATCH: "false"
    DEVTOOLS: $DEVTOOLS_Linux_Unstable

# run tests using the binary built before
testWin512Py37:
  stage: test
  extends: 
    - .stable-debug
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  needs: 
    - windowsBuildDebugPy37
  dependencies: 
    - windowsBuildDebugPy37
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Stable

testWin512UnstablePy37:
  stage: unstableTest
  extends:
    - .unstable-debug  
    - .winTestTemplate
  script:
    - .\tests\unittests\runUnittestsQt512.bat
    - get-content CoverageReport*\index.html
  needs: 
    - windowsBuildDebugUnstablePy37
  dependencies: 
    - windowsBuildDebugUnstablePy37
  variables:
    DEVTOOLS: $DEVTOOLS_Win_Unstable  

testLinux512Py37:
  stage: test
  extends: 
    - .stable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugPy37
  dependencies:
    - linuxBuildDebugPy37
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Stable    

testLinux512UnstablePy37:
  stage: unstableTest
  extends: 
    - .unstable-debug
    - .linuxTestTemplate
  needs: 
    - linuxBuildDebugUnstablePy37
  dependencies:
    - linuxBuildDebugUnstablePy37
  variables:
    DEVTOOLS: $DEVTOOLS_Linux_Unstable   

# deployment
createJobs:
  stage: deploy
  extends:
    - .createJobsTemplate
  dependencies: []
  variables:
    WinReStableJob: windowsBuildReleasePy37
    WinReUnstableJob: windowsBuildReleaseUnstablePy37
    WinDeStableJob: windowsBuildDebugPy37
    WinDeUnstableJob: windowsBuildDebugUnstablePy37
    LinReStableJob: linuxBuildReleasePy37
    LinReUnstableJob: linuxBuildReleaseUnstablePy37
    LinDeStableJob: linuxBuildDebugPy37
    LinDeUnstableJob: linuxBuildDebugUnstablePy37

triggerJobs:
  stage: deploy
  extends: .only-tags-child
  needs:
    - createJobs
  trigger:
    include:
      - artifact: deploy.yml
        job: createJobs
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

# code quality
codingstyle:
  stage: codequality
  extends: .codingStyleTemplate

cppcheck:
  stage: codequality
  extends: .cppCheckReportTemplate

pages:
  stage: badges
  extends: .pageTemplate

package:
  stage: package
  extends: .packageTemplate

# badges
badges:
  stage: badges
  extends: 
    - .stable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugPy37
    - linuxBuildDebugPy37
    - testWin512Py37
    - testLinux512Py37
    - codingstyle

badgesUnstable:
  stage: badges
  extends: 
    - .unstable-only-master
    - .badgeTemplate
  dependencies:
    - windowsBuildDebugUnstablePy37
    - linuxBuildDebugUnstablePy37
    - testWin512UnstablePy37
    - testLinux512UnstablePy37
    - codingstyle
    

